### ISSUE TITLE
Without dedicated GPU

### ISSUE THREAD

**Issue by tamasharasztosi** [baughmann/Catalina-Gigabyte-Designare-Z390-i9-9900k-EFI#1]
Hi!
I would like to use the integrated graphics.
Could you help me out what should I change on your EFI? Do you think I can make it run?
i9-9900K, Z390 Designare, 32GB DDR4 3200Mhz

Thank you!:)

**Comment by baughmann** [comment]
I'm not sure. What chip does the board come with? I couldn't find it right away with a quick Google.

I would've thought that it would work out-of-the-box with WhateverGreen and the right BIOS settings.

**Comment by tamasharasztosi** [comment]
The CPU has Intel Graphics UHD 630 iGPU. I tried tonyxmac’s Unibeast first then a lot of other workaround with no luck. Could you show me some tutorial that could work, Im really a newbie..

**Comment by baughmann** [comment]
Unibeast works for a lot of people, but it's really best to put the EFI folder together yourself. The thing is, things change so much in this community that there's not really a tutorial _per se_--at least not for the process as a whole. The only tutorials I've found to be useful are for individual steps.

The general steps to get a Hackintosh that you are happy with is as follows:

1. Acquire a _mostly_ functioning installation of Macintosh with a working network connection. 
    - For me, the first time I did this I had it running in a VM. It was barely functioning in that VM. 
    - You need this create a bootable USB drive with the MacOS installer on it. Some people have created utilities to do this from Linux, and even from Windows, but I have never found them to work.
    - If I had to do it over again, I would have bought the cheapest used Macbook I could find on Amazon, eBay, or CraigsList that would be upgradable all the way to Catalina.
2. Download MacOS from the Macintosh App Store.
    - https://apps.apple.com/us/app/macos-catalina/id1466841314?mt=12
3. Burn the MacOS disk image to a USB.
    - https://support.apple.com/en-us/HT201372
    - After you've run the terminal command, it may look like nothing is happening. This freaked me out. It take forever to burn the drive, and there's not really any feedback while copying the files. After maybe about 20 minutes of waiting, you can open the "Activity Monitor", go to the "Disk" tab and then click "View" > "All Processes" at the top. Eventually, you will see the "createinstallmedia" task running, and you will see how many bytes it's written. This will tell you roughly how close you are to being finished. This is the most time consuming step from this process, aside from troubleshooting.
4. Add Clover to the USB's EFI partition
    - This is the step where you need to download my repository. After you download it, download Clover Configurator (https://mackie100projects.altervista.org/download/clover-configurator-global-edition/) and move it to your "Applications" directory and open it. "File" > "Open" and then browse to the `config.plist` in the EFI folder you downloaded and follow the instructions for modifying it on the main page for this repository, then com back here.
   - Now, you need to move the EFI folder to your USB drive. In Clover Configurator, you need to go to "Mount EFI" under "Tools" in the sidebar. In the bottom pane of that window, you will see a list of all drives attached to your machine. Find your USB _(make sure you click the right one! You don't want to mess around with your hard drive instead!)_ and click "Mount Partition". You will then be able to click "Open Partition". Then, delete the "EFI" folder inside the "EFI" partition and replace it with the one you got from my repository.
    - What is the "EFI partition" you ask? Your USB drive actually contains multiple partitions. By default when you insert the USB, the data partition containing the disk image is mounted. However, the drive also has a separate "hidden" partition that tells operating systems how to interact with the USB drive. If you put the right software (such as Clover) in the right place on that partition, your computer will be able to boot the disk image.
5. Make the BIOS changes you need to make (try the main page of this repository). It may take some fiddling.
6. Boot the USB drive. (I trust you know how to do this).
    - At the Clover menu, choose "Install macOS"
    - If it doesn't boot to the Clover menu here, the most likely cause is a BIOS misconfiguration. If you copied my EFI and made the changes prescribed then you shouldn't have any trouble yet, granted that your BIOS configuration is correct.
7. Install MacOS normally. 
    - The screen will probably freeze, go black, and generally appear bugging and broken throughout the process. A general rule of thumb is "don't touch it." It's probably working, even though it doesn't look like it. Only start to worry when you haven't seen anything change for ~1hr to ~1.5hr.
    - The machine will probably reboot several times, and you will need to select the appropriate drive at the Clover menu. As soon as you see "macOS" or whatever name you gave to your drive during the installation, choose that one instead of the "Install" option.
8. Setup MacOS. 
    - If you're having graphics issues here, then you're probably missing a driver or a kext, or are using an outdated one. Do some research if this happens.
9. Copy the EFI folder from your USB stick's EFI partition to the EFI partition of the drive to which you installed MacOS.
   - At this point, you know you have a solid EFI folder setup. You need to copy this folder from your USB to your HD. Follow steps similar to those described in step #4.
10. Keep the USB! Don't erase the EFI folder! You never know when you will break the one on your HD while you were tinkering around. If you break the one on your HD, then boot into your USB again and select your HD at the Clover menu to go back and fix your EFI folder.

Another good resource is this TonyMax thread: https://www.tonymacx86.com/threads/success-ongoing-status-of-designare-z390-with-i7-9700k.266065/. If you get stuck, search through the comments or ask someone there.


Let me know if you get stuck anywhere.

**Comment by baughmann** [comment]
@tamasharasztosi Any luck?

**Comment by tamasharasztosi** [comment]
@baughmann It seems like neither of my Ethernet ports are working. Led's are on, but I don't get ip and with tonyxmac's Unibeast when I run into this problem. This is the closest I get to work it I guess. I feel suspicious at the second pic that Install macOS Catalina.app is not in the Applications folder. But still no internet connection. Do you think its fixable with a kext? 
With your tutorial and with several on the forums I always end up with a black screen after some logging, even with fresh kexts and this iGPU EFI:

> https://www.reddit.com/r/hackintosh/comments/dash05/z390_designare_i99900k_rx_580_or_igpu_ultimate/

![IMG_0166](https://user-images.githubusercontent.com/25348566/72224610-8f066800-357c-11ea-9815-259129fb8c50.jpeg)
![IMG_0167](https://user-images.githubusercontent.com/25348566/72224692-6d59b080-357d-11ea-904d-e40a345b730d.jpg)

**Comment by baughmann** [comment]
@tamasharasztosi Did you try both Ethernet ports on the board? Also, have you tried the IntelMausi Ethernet kext?

**Comment by tamasharasztosi** [comment]
@baughmann Finally! I used Unibeast with iMac 19,1 and I formatted the Samsung 970 EVO Plus NVMe SSD to AFS.

**Comment by baughmann** [comment]
@tamasharasztosi Nice. And, crap I forgot to mention that AFS was needed. What fixed it, the IntelMausi kext?

**Comment by samartzis** [comment]
Hello and thank you for the great work!
I have exactly the same build. And I am following all the steps as you mention.

![82943768_285562345966111_2669080202782352584_n](https://user-images.githubusercontent.com/41290664/84569186-31758200-ad8d-11ea-877b-50c2204839c9.jpg)


but this happened, tried couple of workarounds but i cant get over this...
please help!

**Comment by baughmann** [comment]
@samartzis I’m sorry you’re having these issues. I can do a bit of research later today, but I’m afraid today is a busy day for me IRL. In the meantime, I would double-check your BIOS settings.

Another thing: which version of Mac are you downloading? The latest (10.15.5, I believe)? If so, then that’s probably the issue. I’ve recently updated my EFI but did not update this repo. I will do that later today.

**Comment by samartzis** [comment]
Thanks for the rocket-fast answer and sorry if I address dummy questions here but I am a rookie in Hackintosh.
So you already updated in 10.15.5 and updated your efi, but not commited the update in this repo. Is that correct?

**Comment by baughmann** [comment]
@samartzis No worries. Which version of macOS did you download and put on your USB stick? It’s probably the latest.

Yes that’s correct, I’ve updated the EFI on my machine but just haven’t posted the changes. I will do that later today.

**Comment by baughmann** [comment]
@samartzis My apologies, man. I thought that this issue was on the OpenCore version of this EFI. I no longer support the Clover version of the EFI. I have just updated the OpenCore version. I *highly* suggest that you give that one a try instead: https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore

I just updated the OpenCore one. If you have the same exact hardware and BIOS settings as I do it *should* be plug-n-play.

**Comment by samartzis** [comment]
Sure thing dude. I will try that way! Thanks a lot!

**Comment by baughmann** [comment]
@samartzis Sounds good, let me know if it works.

**Comment by atkinsonchristian** [comment]
Hi, congrats on getting your systems working. I've been trying to use Opencore with several different EFI including yours (modifying several parameters of course) with no luck

I've been reading Dortania's guide and do find it better than Clover. I'm fine with finding the Kexts, drivers, and other precompiled files. Also with editing the plist and getting the OS kits and USB installation.

I've also got no graphics card and I''m trying to use the internal graphics. The system obviously works okay for Windows but not so much for the Hackintosh.

I have a Gigabyte Aorus Master, i9-9900K,
Onboard graphics
Adata su650 SSD

I have a kernel panic problem with your EFI and with other peoples EFI's as well. I've tried doing lots of things (different Catalina versions, Openshift files, plist changes) but I can't seem to get past this.

Do you see [anything obvious?
Thanks for any ideas you might have.

Cheers!
![panic](https://user-images.githubusercontent.com/66997810/84760776-31fe5a80-afd1-11ea-81c6-910e6616bc4c.jpeg)
[config.zip](https://github.com/baughmann/Catalina-Gigabyte-Designare-Z390-i9-9900k-EFI/files/4785865/config.zip)
