### ISSUE TITLE
Z390 Designare Ethernet Didnt Work Sir

### ISSUE THREAD

**Issue by screenfreezer** [baughmann/Catalina-Gigabyte-Designare-Z390-i9-9900k-EFI#2]
Dear Boss, 
Everything worked good and there was not even booting screen and direct apple splash screen was loaded but while installing MacOS Ethernet doesnt seem to work. Is there any additional configuration need to be done.

My config is almost same but with RTX 2080 so using intel GPU.

Thanks

**Comment by baughmann** [comment]
The GPU should not affect Ethernet. Are you sure that you have the exact save motherboard?

If you're using this with the latest version of macOS (10.15.5), then you will need to **grab new versions of Clover as well as all kexts and drivers**. I bet you didn't do this. The IntelMausi Ethernet kext that you have is probably old.

Anyway, as I stated [in the README](https://github.com/baughmann/Catalina-Gigabyte-Designare-Z390-i9-9900k-EFI#important-update), I no longer support this repository. You should use the [OpenCore version](https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore) instead.
